import { Rubik } from "next/font/google";
import "./styles/globals.css";
import ClientLayout from "./client-layout";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={rubik.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}